### ISSUE TITLE
The documentation about CLONE_EFFECT and ALTER_EFFECT should mention that negative values result in "no change"

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#137]
Try executing the following piece of code:

```
OUTER_SET state_test = 0x00000001 BOR 0x00000002 BOR 0x00000004 BOR 0x00000008 BOR 0x00000020 BOR 0x00000029 BOR 0x00010000 BOR 0x00100000 BOR 0x80000000

COPY_EXISTING ~SPWI112.spl~ ~override~
  LPF ADD_SPELL_EFFECT
  INT_VAR
    insert_point = 0
    opcode = 318
    target = 2
    parameter1 = state_test
    parameter2 = 138     // STATE bit_eq specified value
    duration = 1
  STR_VAR
    resource = EVAL ~%SOURCE_RES%~
  END
BUT_ONLY
```

Open NearInfinity and have a look at that parameter1: it's a negative value....

The problem seems to be related to **STATE_CONFUSED**....

**Comment by 4Luke4** [comment]
OK, sorry, it seems everything is working as intended.... Apparently the following clause **_negative values result in no change to the corresponding field_** is valid also for ALTER_EFFECT and CLONE_EFFECT...... The problem is that it's not documented....

**Comment by FredrikLindgren** [comment]
There appears to be some confusion here. The reason NI shows parameter1 as negative is because it (presumably) uses signed integers (as does WeiDU) and 0x80000000 (BIT31) is the sign bit, which means all values for which BIT31 are set are interpreted as negative. The value itself is presumably interpreted differently by the game.

Yes, the documentation of ALTER_EFFECT and CLONE_EFFECT should make clear that they don't write negative values. Fixed.
