### ISSUE TITLE
Performance of multi-mod install is awful! Can optimisations be reviewed? Multi-threading While/For Loops?

### ISSUE THREAD

**Issue by Royscw** [WeiDUorg/weidu#175]
As in the title, the installation time of multiple large mods (which is mandatory for my needs) is killing me. Particularly when I keep hitting compatibility issues that then need reinstalls over and over.

I'm overclocking my processor to get that single thread running slightly faster. I'm putting the entire BG folders into a RAMDisk. I'm updating the launch programs to always flag the mod installers as "realtime" priority. It helps, but not by much.

Even with these changes in place, the length of time do to any BWS or EET installations is insane by any standards. 
What can be done to support this? 
Are there any obvious optimisations done to early WeiDU versions that dont apply to modern systems and could be removed?
Can we do any multithreading, particularly for areas such as FOR or WHILE loops, even if we create new versions (i.e. FORt, or WHILEt for the threaded versions)?

I'm willing to support any changes of this nature via coding and testing, but I dont have the time to start trying to understand the project in full then begin updates solo. 

Any support with this would be greatly appreciated. Finding something wrong whilst playing BG EE Trilogy then realising I have to go back and do a full reinstall is killing me and my love for the games.

Thanks

**Comment by FredrikLindgren** [comment]
While I'm sympathetic to your problem, I do not see a ready solution. First, OCaml does not have parallelism. You can have concurrency, but there is no simultaneous execution. [1] Possible exceptions include things like `fork`, but that is not necessarily useful to WeiDU. Second, TP2 is a long way from being thread safe and the existing code-base is in my estimate particularly poorly suited for any attempted retrofitting of concurrency.

Then we get to the other part, that it may be the mods themselves which are bottlenecks. Can you post the `Timings` section of the debug file for one of your slow installs?

1. I have not looked into this in great detail, since preliminary findings were quite discouraging, so maybe I'm wrong on some point.
