### ISSUE TITLE
V247 and SCS not compatible

### ISSUE THREAD

**Issue by RoxanneSHS** [WeiDUorg/weidu#177]
I have used weidu 247 (64bit version) successfully to install any number of mods. However the installation of Sword Coast Stratagems fails fatally. Even when I repair the first error that appears, it immediately chokes on the next step. Installation of SCS with weidu 246 works without problem.
Since SCS is one of the most widely used mods, I think this is worth investigating.

PS - SCS version 33.4 (latest version) was used both with 246 and 247

PPS - I have also received information from other users with the same problem, so we can eliminate a local issue.

**Comment by FredrikLindgren** [comment]
Yes, the issues became apparent shortly after I posted 247. WeiDU chokes on trarefs for VERSION (because MOD_VERSION tries to resolve something that can be a traref before tra refs have been loaded) and SCS et al use TP2_BASE_NAME as a synonym for the mod folder, since, up until 247, TP2_BASE_NAME did not include a file extension, contrary to the documentation.

I'll fix the tra issue and likely change the documentation and behaviour of TP2_BASE_NAME.

**Comment by RoxanneSHS** [comment]
SCS itself is now compatible with weidu 247 BUT ONLY with 247, not with previous versions. The issue for the problem does however also exist with other mods that contain mod version numbers inside tra files. This is a problem to be solved by weidu.
