### ISSUE TITLE
OUTER_SPRINT should behave as OUTER_TEXT_SPRINT when AUTO_EVAL_STRINGS is used

### ISSUE THREAD

**Issue by 4Luke4** [WeiDUorg/weidu#187]
Apparently, `OUTER_SPRINT` does not function correctly when `AUTO_EVAL_STRINGS` is used.

```
AUTO_EVAL_STRINGS

BEGIN "Test"

ACTION_DEFINE_ASSOCIATIVE_ARRAY "test" BEGIN
	"string0=>0", "string1=>1" => "command"
END
ACTION_PHP_EACH "test" AS "arguments" => "command" BEGIN
	OUTER_FOR ("i" = 0; "%i%" <= 1; "i" += 1) BEGIN
		ACTION_IF (VARIABLE_IS_SET "arguments_%i%") BEGIN
			OUTER_SPRINT "current_pair" "%arguments_%i%%"
			PRINT "%current_pair%"
		END
	END
END
```

The aforementioned code will print
```
%arguments_0%

%arguments_1%
```

Instead, if I use `OUTER_TEXT_SPRINT` in place of `OUTER_SPRINT`, then it will correctly print
```
string0=>0

string1=>1
```

**Comment by FredrikLindgren** [comment]
What happens is that with AUTO_EVAL_STRINGS, TEXT_SPRINT gets one EVAL that SPRINT does not. I can't reduce the number of EVALs TEXT_SPRINT gets, or increase the number of EVALs SPRINT gets, without causing unintended consequences. I'll document the interaction, but otherwise this is won't fix. You will have to count the levels of variable nesting and use EVAL until you get the desired result, AUTO_EVAL_STRINGS notwithstanding.
