### ISSUE TITLE
Feature Request: Support for long names and all foreign accents

### ISSUE THREAD

**Issue by Felipefpl** [WeiDUorg/weidu#202]
apparently names like "brazilian portuguese" (please see the last posts of this thread https://github.com/Gibberlings3/widescreen/pull/10) and foreign accents cant be added to mods because of the lack of support for them. Could you please add support for those to solve these problems?

**Comment by FredrikLindgren** [comment]
WeiDU does support language folders like `brazilian portugese`.

I'm unsure which encoding issues you mean. Keep in mind file and folder names "cannot" (air quotes) contain characters outside of ASCII because different operating systems use different encoding systems for their respective file systems, but that is not a WeiDU limitation.
