### ISSUE TITLE
Weidu simply crash

### ISSUE THREAD

**Issue by PowaBanga** [WeiDUorg/weidu#242]
hi everybody !

Maybe i use it wrong, but i have a core dumped when i try to use weidu on my archlinux x86_64 :
```
 powabanga  ~  Games  baldursgate  weidu gemrb-mods/gemrb-tweaks/gemrb-tweaks.tp2 
[1]    254175 bus error (core dumped)  weidu gemrb-mods/gemrb-tweaks/gemrb-tweaks.tp2
```

**Comment by FredrikLindgren** [comment]
I would suggest you try compiling from source. I would guess there is some incompatibility between my build system and your own system.

You might be able to use opam to install the required older version of OCaml, otherwise you may need to compile that from source as well. WeiDU requires an OCaml version between >=4.04 and <=4.11. See, for instance, https://ocaml.org/p/ocaml/4.11.2

The next step is setting up Elkhound. You can check the pre-compiled executable available under Releases. If that doesn't work, it should be straightforward to build from source. Place the executable on your $PATH and set the executable flag.

The WeiDU Readme has some more detailed build instructions.
