### ISSUE TITLE
Installing PVRZ-based MOS and BAM

### ISSUE THREAD

**Issue by FredrikLindgren** [WeiDUorg/weidu#31]
Feature requested [here](http://forums.pocketplane.net/index.php/topic,28880.msg333624.html#msg333624).

**Comment by Argent77** [comment]
This is a working implementation of PVRZ-based BAM/MOS install routines: [pvrz_funcs_v2.tph](https://www.dropbox.com/s/nx573ujr84kivd2/pvrz_funcs_v2.tph?dl=1)

It includes the necessary functions and a few examples how to use them properly. I have also uploaded two mods for testing purposes ([Test mod 1](https://www.dropbox.com/s/diqbiq45vh9i5jx/A7%23TestPvrz.7z?dl=1) and [Test mod 2](https://www.dropbox.com/s/u9pqs1ocy3xd6rg/A7%23TestPvrz2.7z?dl=1)).

I'm not familiar with your policy how to handle unexpected situations, so I have tried to handle them as unobtrusive as possible by using LOG or WARN rather than FAIL depending on the situation.

**Comment by FredrikLindgren** [comment]
I'll try to look this over and integrate this no later than next weekend. I will make some minor changes. Notably, public, documented symbols will be put into the UPPERCASE_NAME_SPACE_WITH_UNDERSCORES. There may have been one or two other things, but I forget (either way, I'll be keeping you informed).

For unexpected situations, I try to use FAIL when the problem is such that the mod cannot be successfully installed without problems arising during game play. WARN should inform the user there may be a problem. He or someone knowledgeable will have to decide if it is a problem (e.g., "special whatever not possible; using default whatever instead") and LOG should be informative for those who look at debug files (which is typically the modder).

**Comment by Argent77** [comment]
I've discovered a small bug in pvrz_funcs_v2.tph at line 387.

The line ```PATCH_IF (min_index = "-1" || max_index == 100000) BEGIN``` has to be replaced by ```PATCH_IF (min_index == 100000 || max_index == "-1") BEGIN```.

**Comment by FredrikLindgren** [comment]
Included. Thanks. I only ended up changing an additional few details concerning variables (e.g., you never need to enclose integers in percentage signs when you use them as integers).
