### ISSUE TITLE
--make-tlk does not emit dialogf

### ISSUE THREAD

**Issue by FredrikLindgren** [WeiDUorg/weidu#84]
Add output path to make dialogf if there are female strings.

**Comment by daktyl** [comment]
Any progress on this one? I currently have one dialog.tra file which includes both male and female strings. Is there any way to produce proper Dialog.tlk and DialogF.tlk using WeiDU from this file other than waiting for the fix from you? Maybe an older WeiDU version doesn't have this problem? Thanks.

**Comment by FredrikLindgren** [comment]
I have not yet had the time to code this. This feature has never existed.

**Comment by daktyl** [comment]
It works, thank you so much! However I noticed that if .tra file contains both male and female strings and the game directory contains only Dialog.tlk, WeiDU will only update Dialog.tlk and won't create DialogF.tlk from scratch.

However putting the DialogF.tlk in the game directory makes it update also DialogF.tlk with new strings. Is it an expected behaviour?

**Comment by FredrikLindgren** [comment]
Yes. --make-tlk will not create a dialogf.tlk in games that do not already have one.

**Comment by daktyl** [comment]
Thank you for the explanation.
