### ISSUE TITLE
Need better logging for if-valid checks

### ISSUE THREAD

**Issue by burner1024** [WeiDUorg/weidu#89]
Currently, many functions use "fj_if_valid", or source_size checks. If there's a file that doesn't pass the check, it's silently skipped, which makes debugging harder in some cases. I think they should go with a "Warning: file xxx is invalid, skipping it" alert in the log.

**Comment by FredrikLindgren** [comment]
The function FJ_CRE_VALIDITY has the variable do_message that will make it emit information about invalid files. The function does not unconditionally initialise this variable, so you can set it in a global scope and it should affect all invocations of the function (unless some other code also sets the variable further down the call chain).

SOURCE_SIZE is a variable used in a generic conditional, so there is nothing that can be done to log that short of chattier code that has an else branch for when the conditional is false.

**Comment by burner1024** [comment]
Hm, I didn't think functions allow to set vars in global scope. That would be part of the solution, yes. Although my point is that I think it should be the case by default.

As for SOURCE_SIZE - that's exactly what I propose, chattier code with an ELSE branch.

**Comment by FredrikLindgren** [comment]
Debug behaviour cannot be default. It is additional behaviour you might want while debugging, but which is undesirable or superfluous at other times. Particularly, there are (or were; I don't know if this a still a problem in the wild today) a lot of known, or practically known, bad files and it is these that this code is intended to screen out. These are not files that should generate warnings, because they are known-bad and would only serve as noise in the debug file.

I'm looking into adding some sort of debug LOG and PRINT statements that could be toggled on and off via the MODDER flag (so at on, you'd get debug info by default), but it's not an entirely clear-cut extension to MODDER so I will have to see where it lands.

**Comment by burner1024** [comment]
This looks like throwing out the baby with the water to me. Because of a few known problem files, all problem files are ignored, when in fact it's them that present interest. The purpose of the log is debug, I don't know how else would it be used.
MODDER is not quite the same thing, because here I specifically mean better logging in the wild.

If you disagree, well, it's your call, so... ok.
Anyway, as a point of interest, I have a lolfixer-based project, which aims to either fix all those files, or remove them (stalled currently, though).

**Comment by FredrikLindgren** [comment]
No. It's trivial to run FJ_CRE_VALIDITY or a SOURCE_SIZE check against all files of a type. Do your testing yourself, or get some volunteers.

**Comment by burner1024** [comment]
Sorry, I don't understand your last comment. I don't think I've implied it wasn't.

**Comment by FredrikLindgren** [comment]
The purpose of the debug file is to provide meaningful information helpful in debugging mods. Spamming it with messages about hopelessly broken files is just noise. If you want that information, you should run a simple mod that reports on it, because it is pretty much only interesting for you and your particular use case. Because it is not interesting information for modders in general, it cannot be provided by default.

**Comment by burner1024** [comment]
I don't think you know that. But like I said, your call.
